[package]
name = "urm"
version = "0.1.0"
authors = ["Junde Yhi <lmy441900@aosc.xyz>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
rocket = "0.4.4"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["helmet", "json", "tera_templates", "mongodb_pool"]
