# Configuration file for URM, the Unified Repository Manager.

[urm]
# The branding text located at the top-left corner in the user interfaces.
# brand = "Unified Repository Manager"

# The product name shown in the user interfaces.
# Default: The package name defined in Cargo.toml.
# product_name = "urm"

# The version number is overridable, but it's not recommended.
# Default: The version defined in Cargo.toml.
# version = "major.minor.patch"

# The base path where URM is supposed to mount on; this is sent to Rocket.
# mount_point = "/"

[urm.collection]
# Name of the MongoDB collection storing product data
# products = "products"

# Name of the MongoDB collection storing repository data
# repositories = "repositories"

# Name of the MongoDB collection storing user data
# users = "users"

# The following table specifies the paths to those common resources used by URM.
# They can be configured to CDNs (by writing URLs), or can be served by this
# server (by writing an absolute path). The defaults are local serving.
[urm.static]
bootstrap_css = "/css/bootstrap.min.css"
bootstrap_bundle_js = "/js/bootstrap.bundle.js"
jquery_js = "/js/jquery.min.js"

[urm.crypto.pbkdf2]
# The iteration count for the PBKDF2 password hashing algorithm
# iterations = 10000
